name: carto_cafat
version: "1.0.0"
config-version: 2
profile: carto_cafat

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  carto_cafat:
    staging:
      +schema: staging
      +materialized: view
    core:
      +schema: core
      +materialized: table
    marts:
      +schema: carto
      +materialized: table

seeds:
  carto_cafat:
    +schema: referentiel
